language: node_js

node_js:
  - "10.24"

before_install:
  - npm i -g npm@6

install: npm install

services:
  -  sqlite3

script:  
  - npm install
  - npm run test

cache:
  directories: [node_modules]

after_success:
  - npm run coverage
  - npm run coveralls
