language: node_js

node_js:
  - "10"

before_install:
  - npm i -g npm@6

install: npm install

services:
  -  sqlite3

cache:
  directories: [node_modules]

script: npm test

after_success: npm run coverage
